apiVersion: ec2.aws.upbound.io/v1beta1
kind: LaunchTemplate
metadata:
  name: {{ .Values.clusterName }}-secondary
spec:
  forProvider:
    region: {{ .Values.region }}
    name: {{ .Values.clusterName }}-secondary
    blockDeviceMappings:
      - deviceName: /dev/sda1
        ebs:
          - volumeSize: 70
    imageId: {{ .Values.ami }}
    instanceType: {{ .Values.instanceType }}
    networkInterfaces:
      - deviceIndex: 0
        securityGroups: 
        {{- range .Values.securityGroupIDs }}
          - {{ . }}
        {{- end }}
        associatePublicIpAddress: "true"
    keyName: {{ .Values.keyName }}
    userData: {{ tpl (.Files.Get "files/cloudinit/secondary.txt") . | b64enc }}
    monitoring:
      - enabled: true
    tags:
      env: {{ .Values.env }}
  deletionPolicy: Delete
  providerConfigRef:
    name: {{ .Values.crossplaneProviderName }}