apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-test
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path
  hostPath:
    path: /cogdata/prometheus
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: prometheus
              operator: In
              values:
                - master
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-test
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
