apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-cluster-monitoring-db-prometheus-cluster-monitoring-0
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /cogdata/prometheus
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: prometheus
              operator: Exists
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-cluster-monitoring-db-prometheus-cluster-monitoring-0
spec:
  storageClassName: "local-storage"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
